version: '3.8'

services:

  backend:
    build: ./backend
    container_name: tscmf-backend
    ports:
      - 5000:5000
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgresql://sam:test123@db:5432/tscmf_db
      - DATABASE_SEED=true
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: tscmf-frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:5000
      - WDS_SOCKET_HOST=127.0.0.1
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=0
      - HOST=0.0.0.0
      - PUBLIC_URL=http://localhost:3000
    depends_on:
      - backend
      
  db:
    image: postgres:15
    ports:
      - 5432:5432
    container_name: tscmf-postgres
    environment:
      - POSTGRES_USER=sam
      - POSTGRES_PASSWORD=test123
      - POSTGRES_DB=tscmf_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin4:
      container_name: my_pgadmin4
      image: dpage/pgadmin4
      restart: "always"
      environment:
        PGADMIN_DEFAULT_EMAIL: "sam@gmail.com"
        PGADMIN_DEFAULT_PASSWORD: "test123"
        PGADMIN_CONFIG_SESSION_EXPIRATION_TIME: 365
        PGADMIN_CONFIG_MAX_SESSION_IDLE_TIME: 60
      volumes:
        - pgadmin4-data:/var/lib/pgadmin
      ports:
        - "5050:80"
      extra_hosts:
        - "host.docker.internal:host-gateway"
        
volumes:
  postgres_data:
  pgadmin4-data: