version: '3.8'

services:

  backend:
    build: ./backend
    container_name: tscmf-backend
    ports:
      - 5000:5000
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgres://sam:test123@db:5432/tscmf_db
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 5000
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: tscmf-frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://backend:8000
      - WDS_SOCKET_HOST=127.0.0.1
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=0
      - HOST=0.0.0.0
      - PUBLIC_URL=http://localhost:3000
    depends_on:
      - backend
      
  db:
    image: postgres:15
    expose:
      - 5432
    container_name: tscmf-postgres
    environment:
      - POSTGRES_USER=sam
      - POSTGRES_PASSWORD=test123
      - POSTGRES_DB=tscmf_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: