"""initial_schema

Revision ID: 3e6524a67ae8
Revises: 
Create Date: 2025-04-01 15:17:06.893337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e6524a67ae8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity',
    sa.Column('entity_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_name', sa.String(), nullable=False),
    sa.Column('entity_address', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('client_type', sa.String(), nullable=True),
    sa.Column('risk_rating', sa.String(), nullable=True),
    sa.Column('onboard_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('entity_id')
    )
    op.create_table('transaction',
    sa.Column('transaction_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('beneficiary', sa.String(), nullable=True),
    sa.Column('product', sa.String(), nullable=True),
    sa.Column('tenor', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('list_of_goods', sa.ARRAY(sa.String()), nullable=True),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_table('entity_limit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('approved_limit', sa.Float(), nullable=True),
    sa.Column('used_limit', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.entity_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event',
    sa.Column('event_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('source_content', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.entity_id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.transaction_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('transaction_entity',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('entity_name', sa.String(), nullable=True),
    sa.Column('entity_address', sa.String(), nullable=True),
    sa.Column('entity_country', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.transaction_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eligibility_check',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('check_timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.event_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exposure_check',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('check_timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.event_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('limits_check',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('check_timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.event_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sanction_check',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('check_timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.event_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sanction_check')
    op.drop_table('limits_check')
    op.drop_table('exposure_check')
    op.drop_table('eligibility_check')
    op.drop_table('transaction_entity')
    op.drop_table('event')
    op.drop_table('entity_limit')
    op.drop_table('transaction')
    op.drop_table('entity')
    # ### end Alembic commands ### 